### ISSUE TITLE
[BUG] Unhandled Expression "season" check log file

### ISSUE THREAD

**Issue by abusayed0206** [mach64/trakt-scrobbler#298]
**Describe the bug**

A clear and concise description of what the bug/error is.

**Desktop (please complete the following information):**
 - Window 11 23H2
 - Python 3.12.3
 - MPC-hc latest

**To Reproduce**

simply stopped working.

**Log file**

<details><summary>Click to see log contents</summary> 
<p>

2024-05-22 14:24:23,744 - ERROR - backlog_cleaner - __init__ - Unhandled exception
Traceback (most recent call last):
  File "C:\Python\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Python\Lib\threading.py", line 1431, in run
    self.function(*self.args, **self.kwargs)
  File "C:\Users\Sayed\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\backlog_cleaner.py", line 50, in clear
    if trakt.add_to_history(**item) is True:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sayed\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\trakt_interface.py", line 149, in add_to_history
    history = prepare_history_data(watched_at, media_info)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sayed\pipx\venvs\trakt-scrobbler\Lib\site-packages\trakt_scrobbler\trakt_interface.py", line 140, in prepare_history_data
    {'number': media_info['season'], 'episodes': [
               ~~~~~~~~~~^^^^^^^^^^
KeyError: 'season'
</p>
</details>


I use the latest beta version. cause, regular version is not working for this [issue](https://github.com/iamkroot/trakt-scrobbler/issues/257#issuecomment-2113784360). now, the beta version stopped working. 
But, when I try to monitor via cmd its working. 
![WindowsTerminal_1of9LXpp6r](https://github.com/iamkroot/trakt-scrobbler/assets/43584104/3e0c5705-d9cc-46d6-be5a-99d0ba45b9b4)

**Comment by iamkroot** [comment]
I guess something is wrong with your backlog file (see https://github.com/iamkroot/trakt-scrobbler/wiki/FAQs#what-happens-when-there-is-no-internet-connection for what it is), if you don't care about it, try deleting the `watched_backlog.json` file from https://github.com/iamkroot/trakt-scrobbler/wiki/FAQs#where-is-the-log-fileother-data-stored) and restart with `trakts start -r`.

Deleting the file will cause the scrobbler to forget some of the events that happened when trakt.tv wasn't reachable, so make sure you add those manually.

**Comment by iamkroot** [comment]
What does `trakts backlog list` give btw?
